Add dimension order arguments for netcdf data object
OpenDA-Association/OpenDA pull request #145
Opened 2020-06-30 16:00 UTC by erikpelgrim

Pull request for meerpeil correction fix.

2020-06-30 16:06 UTC, nilsvanvelzen commented on core/java/src/org/openda/exchange/dataobjects/NetcdfUtils.java
> +import ucar.nc2.*;
Codacy found an issue: [Avoid unused imports such as 'ucar.nc2'](https://app.codacy.com/gh/OpenDA-Association/OpenDA/pullRequest?prid=5780915)

2020-06-30 16:06 UTC, nilsvanvelzen commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones added
============
- core/java/test/org/openda/exchange/dataobjects/NetcdfDataObjectTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OpenDA-Association/OpenDA/pullRequest?prid=5780915&bid=18926811)

2020-07-01 08:44 UTC, aljavrieling requested changes
PLease remove the unused import statement: we do not want to introduce new Codacy issues.

Given the circumstances that OpenDA arrays do not know anything about the grid dimensions they originate from, this option is needed to match column-based and row-based data. The bugfix is OK.

2020-07-01 09:49 UTC, nilsvanvelzen commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- core/java/test/org/openda/exchange/dataobjects/NetcdfDataObjectTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OpenDA-Association/OpenDA/pullRequest?prid=5780915&bid=18926811)

2020-07-01 10:13 UTC, nilsvanvelzen commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Clones added
============
- core/java/test/org/openda/exchange/dataobjects/NetcdfDataObjectTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/OpenDA-Association/OpenDA/pullRequest?prid=5780915&bid=18926811)

2020-07-01 11:18 UTC, merged